### ISSUE TITLE
Loading YOLO requires installing and importing YOLO from ultralytics

### ISSUE THREAD

**Issue by bhomaidan1990** [Samahu/ouster-yolov5-demo#1]
I was not able to run this cell in the notebook on Google Colab:
```py
# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
```
**Solution**
```py
%pip install ultralytics
from ultralytics import YOLO
```

**Comment by Samahu** [comment]
@bhomaidan1990 When we published the notebook it didn't have this issue and we could run it as is. It is probably due to an update on `torch` library side that required this change. Thanks for reporting the problem; it has been fixed with your proposed solution.
